### ISSUE TITLE
No package budgie-1.0 available.

### ISSUE THREAD

**Issue by niyasc** [solus-project/budgie-desktop-examples#1]
Hi,

I am trying to figure out how to work with Budgie panel applets. As a first step, I downloaded this project and tried to build in my system(Fedora 23).

`autogen` script is reporting missing packages `budgie-1.0`. What is this package about? Is it something specifically available for Solus only?

Regards.

**UPDATE**
Problem was solved after installing `budgie-desktop-devel` package.

**Comment by ikeydoherty** [comment]
Yeah its our pkgconfig name
