### ISSUE TITLE
How can I add my python plugin's symbolic icons to the hicolor dir and use them?

### ISSUE THREAD

**Issue by serdarsen** [solus-project/budgie-desktop-examples#10]
I am developing [my budgie plugin](https://github.com/serdarsen/budgie-browser-profile-launcher) based on your [budgie python example](https://github.com/budgie-desktop/budgie-desktop-examples/tree/master/python_project).
 
Now It works with icons in it's own dir. 
I don't know how to save and use symbolic icons.

I tried saving and using my icons to usr/share/icons/hicolor/symbolic/apps or usr/share/icons/ hicolor/scalable/actions manually but the plugin didn't recognise it.

**Comment by Jacob-Vlijm** [comment]
Hi serdarsen, I can help you out, but currently redecorating the house :). Could you post this as a question on Ask Ubuntu? That way it would potentially serve a wider audience. I will then answer tomorrow or day after tomorrow if you ping me, and no one else posted a sufficient answer.

**Comment by serdarsen** [comment]
Ok @Jacob-Vlijm Good luck with :) 
I posted it 
[https://askubuntu.com/questions/1030592/how-can-i-add-my-python-plugins-symbolic-icons-to-the-hicolor-dir-and-use-them](https://askubuntu.com/questions/1030592/how-can-i-add-my-python-plugins-symbolic-icons-to-the-hicolor-dir-and-use-them)

**Comment by Jacob-Vlijm** [comment]
Answered on Ask Ubuntu: https://askubuntu.com/a/1030745/72216

**Comment by serdarsen** [comment]
Hi, thank you so much Jacob Vlijm. I got it, applied, it works
