### ISSUE TITLE
Add setting for applet in Budgie Desktop Setting

### ISSUE THREAD

**Issue by yursan9** [solus-project/budgie-desktop-examples#5]
Sorry, I press `Enter` too soon. 😂 
So, I'm thinking about adding setting too my applet. How can I add setting using Python?

**Comment by lachlan-00** [comment]
I'm looking for this too. All the source for current applets seems to be in vala and the example doesn't have any settings code.

What i've done so far is copy the settings ui from budgie menu and edit it to my needs.
https://github.com/budgie-desktop/budgie-desktop/blob/master/src/applets/budgie-menu/settings.ui

Then i think you need to add the BudgieMentSettings class to your plugin
~~~
class BudgieMenuSettings(GTK.Grid)
    def __init__(self):
        """ NOT sure? """
        self.builder = Gtk.Builder()
        self.builder.add_from_file('settings.ui')
        self.builder.connect_signals(self)
        self.pickbutton = self.builder.get_object('button_icon_pick')
        self.pickentry = self.builder.get_object('entry_icon_pick')
~~~

Still working on it as i'm just trying to ape the code from the vala plugins.

**Comment by yursan9** [comment]
https://github.com/yursan9/budgie-caffeine-applet/blob/master/budgie-caffeine-applet.py.in

If you want to know how to add setting, look at my caffeine applet.

**Comment by lachlan-00** [comment]
That's great, i've managed to add settings UI in very easily following your plugin.
My only question for you is how is setting passed to the CaffeineSetting class?

When i run mine i get an error that settings is null

I've copied pretty much your exact structure of the classes so i'm not sure what i missing.
~~~
return PyLaunchSettings(self.get_applet_settings(self.uuid))

setting.bind("folder-path", chooser, 'get_path',
AttributeError: 'NoneType' object has no attribute 'bind'
~~~

**Comment by lachlan-00** [comment]
Oh, wait that's actually because when i install i need to create the dconf settings.

I was just installing the files and restarting the panel without creating any settings for the applet.

**Comment by yursan9** [comment]
Everything is working fine, right? I'll close this, because I already solve the issue.
