### ISSUE TITLE
Not an issue but a question!!!

### ISSUE THREAD

**Issue by cgiannakidis70** [solus-project/budgie-desktop-examples#9]
I am trying to create an applet in python, following the examples here, and i want to test it.
How to do this? 
Thanks in advance.

**Comment by fossfreedom** [comment]
Save the .plugin and all associated modules to .local/share/budgie-desktop/plugins/yourpluginfolder
Then restart the panel to see the plugin appear in budgie settings

**Comment by cgiannakidis70** [comment]
ok.Thank you.

**Comment by cgiannakidis70** [comment]
With all respect can you help me to solve some problems with my applet.I am not so sure if its running .

**Comment by fossfreedom** [comment]
Link to the code?

**Comment by cgiannakidis70** [comment]
I don't have a link.Its a python script.I followed the examples for  python and it is in entry level.I made a button to open a drop down menu .But  now i have only the button.
Should I paste the code here?
Thanks.

**Comment by fossfreedom** [comment]
Create a github gist or a test github repo

**Comment by cgiannakidis70** [comment]
Ok. This is it.
https://gist.github.com/cgiannakidis70/85d8c7390dc265f2db6a4197fccc3bd3

**Comment by fossfreedom** [comment]
line 35 onwards only adds a button with an image.  I don't see any code here where you have connected the "clicked" event for the button and then added code to respond to that click event.

**Comment by cgiannakidis70** [comment]
So, with all respect, how should I go on with the code. 
Thanks in advance.

**Comment by fossfreedom** [comment]
def _respond_to_clicked(self, *args):
         # add the code here to display or do what you want
         # it really is up to you what you want to do with the clicked event
         print ("Hi you have clicked me")

    self.button.connect('clicked', self._respond_to_clicked)

**Comment by cgiannakidis70** [comment]
OK .Thanks a lot.I'll continue this as you said.
